// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "gamelieelearn/expense-tracker-api-go/domain"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepositoryInt type
type ExpenseRepository struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) Store(ctx context.Context, expense *domain.Expense) error {
	ret := _m.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
