// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gamelieelearn/expense-tracker-api-go/config"
	"gamelieelearn/expense-tracker-api-go/internal/http"
	"gamelieelearn/expense-tracker-api-go/internal/repository/sqlite"
	"gamelieelearn/expense-tracker-api-go/service"
)

// Injectors from wire.go:

func InitializeContainer() (Container, error) {
	configConfig := config.NewConfig()
	userRepository := sqlite.NewUserRepository()
	expenseRepository := sqlite.NewExpenseRepository()
	userService := service.NewUserService(userRepository)
	expenseService, err := service.NewExpenseService(expenseRepository, userService)
	if err != nil {
		return Container{}, err
	}
	userHandler := http.NewUserHandler(userService)
	expenseHandler := http.NewExpenseHandler(expenseService)
	container := NewContainer(configConfig, userRepository, expenseRepository, userService, expenseService, userHandler, expenseHandler)
	return container, nil
}
